version: 2.1

orbs:
  # See https://github.com/CircleCI-Public/ruby-orb
  ruby: circleci/ruby@1.3.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      # See https://github.com/CircleCI-Public/cimg-ruby
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test


workflows:
  build_and_test:
    jobs:
      - test:
          # See https://circleci.com/blog/circleci-matrix-jobs/
          matrix:
            parameters:
              ruby-version: ["2.7", "3.0", "3.1"]  # No manifest exists for: 2.9, 2.8, 2.3, 2.0
