version: 2.1

orbs:
  # See https://github.com/CircleCI-Public/ruby-orb
  ruby: circleci/ruby@1.3.0

jobs:
  test:
    parameters:
      ruby-version:
        type: string
    docker:
      # See https://github.com/CircleCI-Public/cimg-ruby
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

  integration:
    parameters:
      ruby-version:
        type: string
      rails-version:
        type: string
    docker:
      # See https://github.com/CircleCI-Public/cimg-ruby
      - image: cimg/ruby:<< parameters.ruby-version >>
    working_directory: ~/sitemap_generator/integration
    steps:
      - checkout:
          path: ~/sitemap_generator
      - run:
          name: Install appraisal
          command: |
            gem install appraisal
      - run:
          name: Generate gemfiles
          command: bundle exec appraisal generate
      - run:
          name: Install Rails dependencies
          environment:
            BUNDLE_GEMFILE: "./gemfiles/rails_<< parameters.rails-version >>.gemfile"
          command: |
            if [[ -f $BUNDLE_GEMFILE ]]
            then
                bundle install --path vendor/bundle
            fi
      - run:
          name: Run Rails integration tests
          environment:
            BUNDLE_GEMFILE: "./gemfiles/rails_<< parameters.rails-version >>.gemfile"
          command: |
            if [[ -f $BUNDLE_GEMFILE ]]
            then
                bundle exec rspec
            fi
workflows:
  build_and_test:
    jobs:
      - test:
          # See https://circleci.com/blog/circleci-matrix-jobs/
          matrix:
            parameters:
              ruby-version: ["2.7", "3.0", "3.1"]  # No manifest exists for: 2.9, 2.8, 2.3, 2.0
      - integration:
          # See https://circleci.com/blog/circleci-matrix-jobs/
          matrix:
            parameters:
              ruby-version: ["2.7", "3.0", "3.1"]  # No manifest exists for: 2.9, 2.8, 2.3, 2.0
              rails-version: ["5_2", "6_0", "6_1", "7_0"]
